from typing import Dict, List


# ============================================================
# JOB FIELD SKILL CATALOG
# ============================================================
#
# These are the canonical skills required/expected for each
# job field.
#
# IMPORTANT:
# - These are NOT generated by Gemini.
# - These are application-controlled reference data.
# - Resume skills are matched against these canonical skills.
#
# ============================================================


JOB_FIELDS: Dict[str, Dict[str, List[str]]] = {

    # --------------------------------------------------------
    # 1. SOFTWARE ENGINEERING
    # --------------------------------------------------------

    "software_engineering": {
        "name": "Software Engineering",

        "skills": [
            "Programming",
            "Object-Oriented Programming",
            "Data Structures",
            "Algorithms",
            "Git",
            "Version Control",
            "REST APIs",
            "Unit Testing",
            "Integration Testing",
            "Debugging",
            "Software Design",
            "Database Fundamentals",
            "Problem Solving",
        ],
    },


    # --------------------------------------------------------
    # 2. BACKEND DEVELOPMENT
    # --------------------------------------------------------

    "backend_development": {
        "name": "Backend Development",

        "skills": [
            "Java",
            "Spring Boot",
            "Node.js",
            "Python",
            "REST APIs",
            "SQL",
            "PostgreSQL",
            "MySQL",
            "Redis",
            "Microservices",
            "Authentication",
            "Authorization",
            "API Design",
            "Unit Testing",
            "Integration Testing",
            "Docker",
            "Git",
        ],
    },


    # --------------------------------------------------------
    # 3. FRONTEND DEVELOPMENT
    # --------------------------------------------------------

    "frontend_development": {
        "name": "Frontend Development",

        "skills": [
            "JavaScript",
            "TypeScript",
            "React",
            "HTML",
            "CSS",
            "UI Development",
            "Responsive Design",
            "State Management",
            "REST APIs",
            "Web Accessibility",
            "Frontend Testing",
            "Git",
        ],
    },


    # --------------------------------------------------------
    # 4. FULL STACK DEVELOPMENT
    # --------------------------------------------------------

    "full_stack_development": {
        "name": "Full Stack Development",

        "skills": [
            "JavaScript",
            "TypeScript",
            "React",
            "HTML",
            "CSS",
            "Java",
            "Spring Boot",
            "Node.js",
            "REST APIs",
            "SQL",
            "PostgreSQL",
            "Git",
            "Unit Testing",
            "Integration Testing",
            "Authentication",
            "Authorization",
            "Docker",
        ],
    },


    # --------------------------------------------------------
    # 5. DEVOPS / CLOUD ENGINEERING
    # --------------------------------------------------------

    "devops_cloud": {
        "name": "DevOps / Cloud Engineering",

        "skills": [
            "Linux",
            "Bash",
            "Docker",
            "Kubernetes",
            "CI/CD",
            "GitHub Actions",
            "AWS",
            "Terraform",
            "Infrastructure as Code",
            "Networking",
            "Monitoring",
            "Logging",
            "Containerization",
            "Git",
        ],
    },


    # --------------------------------------------------------
    # 6. CLOUD ARCHITECTURE
    # --------------------------------------------------------

    "cloud_architecture": {
        "name": "Cloud Architecture",

        "skills": [
            "AWS",
            "Azure",
            "GCP",
            "Cloud Architecture",
            "VPC",
            "Networking",
            "IAM",
            "Compute",
            "Storage",
            "Cloud Databases",
            "Load Balancing",
            "High Availability",
            "Scalability",
            "Fault Tolerance",
            "Cloud Security",
            "Terraform",
            "Infrastructure as Code",
            "Disaster Recovery",
        ],
    },


    # --------------------------------------------------------
    # 7. DATA ENGINEERING
    # --------------------------------------------------------

    "data_engineering": {
        "name": "Data Engineering",

        "skills": [
            "Python",
            "SQL",
            "ETL",
            "Data Pipelines",
            "Data Warehousing",
            "Apache Spark",
            "Apache Kafka",
            "Apache Airflow",
            "PostgreSQL",
            "Data Modeling",
            "Cloud Data Services",
            "Git",
            "Docker",
        ],
    },


    # --------------------------------------------------------
    # 8. AI / MACHINE LEARNING
    # --------------------------------------------------------

    "ai_machine_learning": {
        "name": "AI / Machine Learning",

        "skills": [
            "Python",
            "NumPy",
            "Pandas",
            "Scikit-learn",
            "TensorFlow",
            "PyTorch",
            "Machine Learning",
            "Deep Learning",
            "Statistics",
            "Data Preprocessing",
            "Model Evaluation",
            "Natural Language Processing",
            "Computer Vision",
            "Git",
        ],
    },


    # --------------------------------------------------------
    # 9. CYBERSECURITY
    # --------------------------------------------------------

    "cybersecurity": {
        "name": "Cybersecurity",

        "skills": [
            "Networking",
            "Linux",
            "IAM",
            "Authentication",
            "Authorization",
            "Cryptography",
            "Vulnerability Assessment",
            "Penetration Testing",
            "OWASP",
            "Security Monitoring",
            "SIEM",
            "Incident Response",
            "Cloud Security",
            "Security Engineering",
            "Git",
        ],
    },


    # --------------------------------------------------------
    # 10. QA / TEST ENGINEERING
    # --------------------------------------------------------

    "qa_testing": {
        "name": "QA / Test Engineering",

        "skills": [
            "Manual Testing",
            "Test Automation",
            "Selenium",
            "Playwright",
            "API Testing",
            "SQL",
            "Unit Testing",
            "Integration Testing",
            "Regression Testing",
            "Test Design",
            "CI/CD",
            "Bug Tracking",
            "Git",
        ],
    },
}


# ============================================================
# SKILL ALIASES
# ============================================================
#
# Purpose:
# Convert different ways of writing the SAME skill into
# one canonical skill.
#
# Example:
#
# "Golang"
# "Go (Golang)"
#      ↓
#     "Go"
#
# IMPORTANT:
# Do NOT add aliases that represent different skills.
#
# Example:
#
# GitHub != Git
# Docker != Containerization
# Kubernetes != Docker
#
# ============================================================


SKILL_ALIASES: Dict[str, List[str]] = {

    # --------------------------------------------------------
    # General Software Engineering
    # --------------------------------------------------------

    "Programming": [
        "Programming",
        "Programming Languages",
        "Software Programming",
        "Coding",
    ],

    "Object-Oriented Programming": [
        "OOP",
        "Object Oriented Programming",
        "Object-Oriented Programming",
        "Object Oriented Design",
    ],

    "Data Structures": [
        "Data Structure",
        "Data Structures",
    ],

    "Algorithms": [
        "Algorithm",
        "Algorithms",
        "Algorithm Design",
    ],

    "Git": [
        "Git",
        "Git SCM",
    ],

    "Version Control": [
        "Version Control",
        "Version-Control",
        "Source Control",
    ],

    "REST APIs": [
        "REST",
        "REST API",
        "REST APIs",
        "RESTful API",
        "RESTful APIs",
        "REST API Development",
    ],

    "Unit Testing": [
        "Unit Testing",
        "Unit Test",
        "Unit Tests",
    ],

    "Integration Testing": [
        "Integration Testing",
        "Integration Test",
        "Integration Tests",
    ],

    "Debugging": [
        "Debugging",
        "Debug",
        "Software Debugging",
    ],

    "Software Design": [
        "Software Design",
        "Software Engineering Design",
    ],

    "Database Fundamentals": [
        "Database Fundamentals",
        "Database Concepts",
        "Database Basics",
    ],

    "Problem Solving": [
        "Problem Solving",
        "Problem-Solving",
    ],


    # --------------------------------------------------------
    # Programming Languages
    # --------------------------------------------------------

    "Java": [
        "Java",
        "Java Programming",
    ],

    "Go": [
        "Go",
        "Golang",
        "Go (Golang)",
        "Go Programming",
        "Go Language",
    ],

    "Python": [
        "Python",
        "Python 3",
        "Python Programming",
    ],

    "JavaScript": [
        "JavaScript",
        "JS",
        "Java Script",
    ],

    "TypeScript": [
        "TypeScript",
        "TS",
        "Type Script",
    ],

    "C++": [
        "C++",
        "CPP",
        "C Plus Plus",
    ],

    "C": [
        "C",
        "C Programming",
        "C Language",
    ],


    # --------------------------------------------------------
    # Backend Technologies
    # --------------------------------------------------------

    "Spring Boot": [
        "Spring Boot",
        "SpringBoot",
    ],

    "Node.js": [
        "Node.js",
        "NodeJS",
        "Node JS",
    ],

    "SQL": [
        "SQL",
        "Structured Query Language",
    ],

    "PostgreSQL": [
        "PostgreSQL",
        "Postgres",
        "PostgreSQL Database",
        "Postgres Database",
    ],

    "MySQL": [
        "MySQL",
        "My SQL",
        "MySQL Database",
    ],

    "Redis": [
        "Redis",
        "Redis Cache",
        "Redis Database",
    ],

    "Microservices": [
        "Microservices",
        "Microservice",
        "Microservice Architecture",
        "Microservices Architecture",
    ],

    "Authentication": [
        "Authentication",
        "User Authentication",
    ],

    "Authorization": [
        "Authorization",
        "Access Control",
    ],

    "API Design": [
        "API Design",
        "API Designing",
        "REST API Design",
    ],


    # --------------------------------------------------------
    # Frontend
    # --------------------------------------------------------

    "React": [
        "React",
        "React.js",
        "ReactJS",
    ],

    "HTML": [
        "HTML",
        "HTML5",
    ],

    "CSS": [
        "CSS",
        "CSS3",
    ],

    "UI Development": [
        "UI Development",
        "User Interface Development",
        "UI Design",
    ],

    "Responsive Design": [
        "Responsive Design",
        "Responsive Web Design",
    ],

    "State Management": [
        "State Management",
        "Frontend State Management",
    ],

    "Web Accessibility": [
        "Web Accessibility",
        "Accessibility",
        "Web Accessiblity",
    ],

    "Frontend Testing": [
        "Frontend Testing",
        "Front-end Testing",
        "UI Testing",
    ],


    # --------------------------------------------------------
    # DevOps / Cloud
    # --------------------------------------------------------

    "Linux": [
        "Linux",
        "Linux OS",
        "GNU/Linux",
        "Ubuntu Linux",
    ],

    "Bash": [
        "Bash",
        "Bash Scripting",
        "Bash Script",
        "Shell Scripting",
        "Shell Script",
    ],

    "Docker": [
        "Docker",
        "Docker Engine",
        "Docker Containers",
    ],

    "Kubernetes": [
        "Kubernetes",
        "K8s",
        "K8",
    ],

    "CI/CD": [
        "CI/CD",
        "CI CD",
        "CI/CD Pipelines",
        "CI CD Pipelines",
        "CI/CD Pipeline",
        "Continuous Integration",
        "Continuous Delivery",
        "Continuous Deployment",
        "Continuous Integration and Continuous Delivery",
        "Continuous Integration and Continuous Deployment",
    ],

    "GitHub Actions": [
        "GitHub Actions",
        "GitHub Action",
    ],

    "AWS": [
        "AWS",
        "Amazon Web Services",
        "Amazon AWS",
    ],

    "Azure": [
        "Azure",
        "Microsoft Azure",
        "Microsoft Azure Cloud",
    ],

    "GCP": [
        "GCP",
        "Google Cloud Platform",
        "Google Cloud",
        "Google Cloud Platform (GCP)",
    ],

    "Terraform": [
        "Terraform",
        "HashiCorp Terraform",
        "Hashicorp Terraform",
    ],

    "Infrastructure as Code": [
        "Infrastructure as Code",
        "Infrastructure-as-Code",
        "IaC",
    ],

    "Networking": [
        "Networking",
        "Computer Networking",
        "Network Engineering",
    ],

    "Monitoring": [
        "Monitoring",
        "System Monitoring",
        "Application Monitoring",
        "Infrastructure Monitoring",
    ],

    "Logging": [
        "Logging",
        "Application Logging",
        "System Logging",
        "Centralized Logging",
    ],

    "Containerization": [
        "Containerization",
        "Containerisation",
        "Containerized Applications",
        "Containerised Applications",
    ],


    # --------------------------------------------------------
    # Cloud Architecture
    # --------------------------------------------------------

    "Cloud Architecture": [
        "Cloud Architecture",
        "Cloud Architectures",
    ],

    "VPC": [
        "VPC",
        "Virtual Private Cloud",
        "AWS VPC",
    ],

    "IAM": [
        "IAM",
        "Identity and Access Management",
        "AWS IAM",
    ],

    "Compute": [
        "Compute",
        "Cloud Compute",
        "Cloud Computing",
    ],

    "Storage": [
        "Storage",
        "Cloud Storage",
    ],

    "Cloud Databases": [
        "Cloud Databases",
        "Cloud Database",
        "Managed Cloud Databases",
    ],

    "Load Balancing": [
        "Load Balancing",
        "Load Balancer",
        "Load Balancers",
    ],

    "High Availability": [
        "High Availability",
        "High-Availability",
        "HA",
    ],

    "Scalability": [
        "Scalability",
        "System Scalability",
        "Cloud Scalability",
    ],

    "Fault Tolerance": [
        "Fault Tolerance",
        "Fault-Tolerant Systems",
        "Fault Tolerant Systems",
    ],

    "Cloud Security": [
        "Cloud Security",
        "Cloud Security Engineering",
    ],

    "Disaster Recovery": [
        "Disaster Recovery",
        "DR",
        "Disaster-Recovery",
    ],


    # --------------------------------------------------------
    # Data Engineering
    # --------------------------------------------------------

    "ETL": [
        "ETL",
        "Extract Transform Load",
        "Extract, Transform, Load",
    ],

    "Data Pipelines": [
        "Data Pipelines",
        "Data Pipeline",
    ],

    "Data Warehousing": [
        "Data Warehousing",
        "Data Warehouse",
        "Data Warehouses",
    ],

    "Apache Spark": [
        "Apache Spark",
        "Spark",
        "Spark Framework",
    ],

    "Apache Kafka": [
        "Apache Kafka",
        "Kafka",
    ],

    "Apache Airflow": [
        "Apache Airflow",
        "Airflow",
    ],

    "Data Modeling": [
        "Data Modeling",
        "Data Modelling",
    ],

    "Cloud Data Services": [
        "Cloud Data Services",
        "Cloud Data Service",
    ],


    # --------------------------------------------------------
    # AI / Machine Learning
    # --------------------------------------------------------

    "NumPy": [
        "NumPy",
        "Numpy",
    ],

    "Pandas": [
        "Pandas",
        "Pandas Python",
    ],

    "Scikit-learn": [
        "Scikit-learn",
        "Scikit Learn",
        "ScikitLearn",
        "sklearn",
    ],

    "TensorFlow": [
        "TensorFlow",
        "Tensor Flow",
    ],

    "PyTorch": [
        "PyTorch",
        "Py Torch",
    ],

    "Machine Learning": [
        "Machine Learning",
        "Machine-Learning",
        "ML",
    ],

    "Deep Learning": [
        "Deep Learning",
        "Deep-Learning",
        "DL",
    ],

    "Statistics": [
        "Statistics",
        "Statistical Analysis",
    ],

    "Data Preprocessing": [
        "Data Preprocessing",
        "Data Pre-Processing",
        "Data Preparation",
    ],

    "Model Evaluation": [
        "Model Evaluation",
        "Model Assessment",
    ],

    "Natural Language Processing": [
        "Natural Language Processing",
        "NLP",
    ],

    "Computer Vision": [
        "Computer Vision",
        "CV",
    ],


    # --------------------------------------------------------
    # Cybersecurity
    # --------------------------------------------------------

    "Cryptography": [
        "Cryptography",
        "Cryptographic Techniques",
    ],

    "Vulnerability Assessment": [
        "Vulnerability Assessment",
        "Vulnerability Testing",
    ],

    "Penetration Testing": [
        "Penetration Testing",
        "Pen Testing",
        "Pentesting",
        "Penetration Testing (Pentesting)",
    ],

    "OWASP": [
        "OWASP",
        "OWASP Security",
    ],

    "Security Monitoring": [
        "Security Monitoring",
        "Security Operations Monitoring",
    ],

    "SIEM": [
        "SIEM",
        "Security Information and Event Management",
    ],

    "Incident Response": [
        "Incident Response",
        "Security Incident Response",
    ],

    "Security Engineering": [
        "Security Engineering",
        "Cybersecurity Engineering",
    ],


    # --------------------------------------------------------
    # QA / Testing
    # --------------------------------------------------------

    "Manual Testing": [
        "Manual Testing",
        "Manual Test",
        "Manual QA",
    ],

    "Test Automation": [
        "Test Automation",
        "Automated Testing",
        "Automation Testing",
    ],

    "Selenium": [
        "Selenium",
        "Selenium WebDriver",
    ],

    "Playwright": [
        "Playwright",
        "Microsoft Playwright",
    ],

    "API Testing": [
        "API Testing",
        "API Test",
        "REST API Testing",
    ],

    "Regression Testing": [
        "Regression Testing",
        "Regression Test",
    ],

    "Test Design": [
        "Test Design",
        "Test Case Design",
        "Test Scenario Design",
    ],

    "Bug Tracking": [
        "Bug Tracking",
        "Defect Tracking",
        "Issue Tracking",
    ],
}


# ============================================================
# RELATED SKILLS
# ============================================================
#
# These are NOT exact matches.
#
# They can be used later by the Skill Gap Engine to classify
# a skill as "Related" / "Partial" rather than "Matched".
#
# Example:
#
# Candidate:
#     AWS
#
# Required:
#     Cloud Architecture
#
# AWS should NOT become an exact Cloud Architecture match.
#
# Instead:
#
#     Cloud Architecture -> Partial / Related
#
# ============================================================


RELATED_SKILLS: Dict[str, List[str]] = {

    # --------------------------------------------------------
    # Software Engineering
    # --------------------------------------------------------

    "Software Design": [
        "System Design",
        "Software Architecture",
        "Microservices",
        "Distributed Systems",
    ],

    "Problem Solving": [
        "Algorithms",
        "Data Structures",
        "Debugging",
    ],

    "Programming": [
        "Java",
        "Go",
        "Python",
        "C",
        "C++",
        "JavaScript",
        "TypeScript",
    ],


    # --------------------------------------------------------
    # Backend
    # --------------------------------------------------------

    "REST APIs": [
        "API Design",
        "HTTP",
        "Web Services",
    ],

    "Microservices": [
        "Distributed Systems",
        "Event-Driven Architecture",
        "Service-Oriented Architecture",
    ],

    "Authentication": [
        "Authorization",
        "IAM",
        "Security",
    ],

    "Authorization": [
        "Authentication",
        "IAM",
        "Access Control",
    ],


    # --------------------------------------------------------
    # DevOps
    # --------------------------------------------------------

    "DevOps": [
        "Linux",
        "Docker",
        "Kubernetes",
        "CI/CD",
        "Terraform",
        "Infrastructure as Code",
    ],

    "Containerization": [
        "Docker",
        "Kubernetes",
        "Container Orchestration",
    ],

    "Kubernetes": [
        "Containerization",
        "Docker",
        "Container Orchestration",
    ],

    "Infrastructure as Code": [
        "Terraform",
        "Cloud Infrastructure",
        "Cloud Architecture",
    ],

    "Cloud Architecture": [
        "AWS",
        "Azure",
        "GCP",
        "Cloud Infrastructure",
        "Infrastructure as Code",
        "Terraform",
    ],

    "Networking": [
        "TCP/IP",
        "HTTP",
        "DNS",
        "VPC",
        "Load Balancing",
        "Network Security",
    ],

    "Monitoring": [
        "Observability",
        "Metrics",
        "Logging",
        "Alerting",
    ],

    "Logging": [
        "Monitoring",
        "Observability",
        "Centralized Logging",
    ],


    # --------------------------------------------------------
    # Cloud
    # --------------------------------------------------------

    "High Availability": [
        "Fault Tolerance",
        "Load Balancing",
        "Redundancy",
        "Disaster Recovery",
    ],

    "Fault Tolerance": [
        "High Availability",
        "Redundancy",
        "Disaster Recovery",
    ],

    "Cloud Security": [
        "IAM",
        "Authentication",
        "Authorization",
        "Network Security",
    ],


    # --------------------------------------------------------
    # Data Engineering
    # --------------------------------------------------------

    "Data Pipelines": [
        "ETL",
        "Apache Airflow",
        "Apache Kafka",
        "Data Processing",
    ],

    "Data Warehousing": [
        "Data Modeling",
        "SQL",
        "Data Engineering",
    ],


    # --------------------------------------------------------
    # AI / ML
    # --------------------------------------------------------

    "Machine Learning": [
        "Python",
        "NumPy",
        "Pandas",
        "Scikit-learn",
        "Statistics",
        "Data Preprocessing",
        "Model Evaluation",
    ],

    "Deep Learning": [
        "Machine Learning",
        "TensorFlow",
        "PyTorch",
        "Neural Networks",
    ],

    "Natural Language Processing": [
        "Machine Learning",
        "Deep Learning",
        "Python",
    ],

    "Computer Vision": [
        "Machine Learning",
        "Deep Learning",
        "Python",
    ],


    # --------------------------------------------------------
    # Cybersecurity
    # --------------------------------------------------------

    "Security Engineering": [
        "Cybersecurity",
        "Cloud Security",
        "Network Security",
        "Application Security",
    ],

    "Penetration Testing": [
        "Vulnerability Assessment",
        "OWASP",
        "Security Testing",
    ],

    "Cloud Security": [
        "IAM",
        "Networking",
        "Authentication",
        "Authorization",
    ],


    # --------------------------------------------------------
    # QA
    # --------------------------------------------------------

    "Test Automation": [
        "Selenium",
        "Playwright",
        "API Testing",
        "CI/CD",
    ],

    "API Testing": [
        "REST APIs",
        "API Design",
        "Postman",
        "HTTP",
    ],

    "Unit Testing": [
        "Integration Testing",
        "Test Automation",
        "Test Design",
    ],

    "Integration Testing": [
        "Unit Testing",
        "API Testing",
        "Test Automation",
    ],
}


# ============================================================
# HELPER FUNCTIONS
# ============================================================


def get_job_field(
    field: str,
) -> Dict[str, List[str]]:

    return JOB_FIELDS.get(
        field,
        {
            "name": field,
            "skills": [],
        },
    )


def get_required_skills(
    field: str,
) -> List[str]:

    return get_job_field(
        field
    ).get(
        "skills",
        [],
    )


def get_skill_aliases(
    skill: str,
) -> List[str]:

    return SKILL_ALIASES.get(
        skill,
        [],
    )


def get_related_skills(
    skill: str,
) -> List[str]:

    return RELATED_SKILLS.get(
        skill,
        [],
    )


def get_all_job_fields(
) -> Dict[str, Dict[str, List[str]]]:

    return JOB_FIELDS


def get_job_field_names(
) -> Dict[str, str]:

    return {
        field_key: field_data.get(
            "name",
            field_key,
        )
        for field_key, field_data in JOB_FIELDS.items()
    }