-- Baseline schema: everything the application had before Flyway.
--
-- Generated from the running development database with
--   pg_dump --schema-only --no-owner --no-privileges
-- and then tidied: the dump's SET/\restrict preamble is dropped, and
-- Hibernate's generated constraint names (uk6dotkott2kjsp8vw4d0m25fb7
-- and friends) are replaced with readable ones. Hibernate's
-- ddl-auto=validate checks tables, columns and types - never
-- constraint names - so the rename is safe.
--
-- IMPORTANT: on a database that already existed before Flyway was
-- introduced, this file never runs. Such a database is stamped at
-- version 1 by spring.flyway.baseline-on-migrate, because its schema
-- is already exactly what this file would have produced. Only V2 and
-- later apply there. Anything that must reach BOTH an existing and a
-- fresh database therefore belongs in a later migration, not here.


-- ==================================================================
-- users
-- ==================================================================

CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    email      character varying(255) NOT NULL,
    name       character varying(255) NOT NULL,
    password   character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    role       character varying(32) DEFAULT 'CANDIDATE' NOT NULL,
    is_active  boolean DEFAULT true NOT NULL,

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check
        CHECK (role IN ('CANDIDATE', 'RECRUITER', 'ADMIN'))
);


-- ==================================================================
-- resumes
-- ==================================================================

CREATE TABLE resumes (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    content_type       character varying(255) NOT NULL,
    extracted_text     text,
    file_path          character varying(255) NOT NULL,
    file_size          bigint NOT NULL,
    original_file_name character varying(255) NOT NULL,
    processing_status  character varying(255) NOT NULL,
    stored_file_name   character varying(255) NOT NULL,
    updated_at         timestamp(6) without time zone,
    uploaded_at        timestamp(6) without time zone NOT NULL,
    user_id            bigint NOT NULL,

    CONSTRAINT resumes_pkey PRIMARY KEY (id),
    CONSTRAINT fk_resumes_user FOREIGN KEY (user_id) REFERENCES users (id)
);


-- ==================================================================
-- resume_analysis
--
-- score is kept nullable on purpose: the AI service stopped returning
-- one, and a NOT NULL column here used to fail every analysis insert.
-- ==================================================================

CREATE TABLE resume_analysis (
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    score     integer,
    summary   text,
    resume_id bigint NOT NULL,

    CONSTRAINT resume_analysis_pkey PRIMARY KEY (id),
    CONSTRAINT uk_resume_analysis_resume UNIQUE (resume_id),
    CONSTRAINT fk_resume_analysis_resume
        FOREIGN KEY (resume_id) REFERENCES resumes (id)
);


-- ==================================================================
-- resume_analysis element collections
-- ==================================================================

CREATE TABLE resume_analysis_skills (
    analysis_id bigint NOT NULL,
    skill       character varying(255),

    CONSTRAINT fk_resume_analysis_skills
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);

CREATE TABLE resume_analysis_certifications (
    analysis_id   bigint NOT NULL,
    certification character varying(255),

    CONSTRAINT fk_resume_analysis_certifications
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);

CREATE TABLE resume_analysis_education (
    analysis_id bigint NOT NULL,
    degree      character varying(255),
    field       character varying(255),
    institution character varying(255),
    year        character varying(255),

    CONSTRAINT fk_resume_analysis_education
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);

CREATE TABLE resume_analysis_experience (
    analysis_id bigint NOT NULL,
    company     character varying(255),
    description text,
    duration    character varying(255),
    role        character varying(255),

    CONSTRAINT fk_resume_analysis_experience
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);

CREATE TABLE resume_analysis_recommended_fields (
    analysis_id      bigint NOT NULL,
    job_field        character varying(255),
    match_percentage integer,
    job_field_name   character varying(255),

    CONSTRAINT fk_resume_analysis_recommended_fields
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);


-- ==================================================================
-- resume_analysis_projects
-- ==================================================================

CREATE TABLE resume_analysis_projects (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    description text,
    name        character varying(255),
    analysis_id bigint NOT NULL,

    CONSTRAINT resume_analysis_projects_pkey PRIMARY KEY (id),
    CONSTRAINT fk_resume_analysis_projects_analysis
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);

CREATE TABLE resume_analysis_project_technologies (
    project_id bigint NOT NULL,
    technology character varying(255),

    CONSTRAINT fk_resume_analysis_project_technologies
        FOREIGN KEY (project_id) REFERENCES resume_analysis_projects (id)
);


-- ==================================================================
-- Legacy analysis tables
--
-- No entity maps these any more - the AI service stopped returning
-- the fields. They are recreated here so that a fresh database is
-- structurally identical to the existing ones, and so that dropping
-- them later is a deliberate migration rather than an accidental
-- divergence between environments. ddl-auto=validate ignores tables
-- that no entity maps.
-- ==================================================================

CREATE TABLE resume_analysis_strengths (
    analysis_id bigint NOT NULL,
    strength    character varying(255),

    CONSTRAINT fk_resume_analysis_strengths
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);

CREATE TABLE resume_analysis_weaknesses (
    analysis_id bigint NOT NULL,
    weakness    character varying(255),

    CONSTRAINT fk_resume_analysis_weaknesses
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);

CREATE TABLE resume_analysis_missing_skills (
    analysis_id   bigint NOT NULL,
    missing_skill character varying(255),

    CONSTRAINT fk_resume_analysis_missing_skills
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);

CREATE TABLE resume_analysis_recommendations (
    analysis_id    bigint NOT NULL,
    recommendation character varying(255),

    CONSTRAINT fk_resume_analysis_recommendations
        FOREIGN KEY (analysis_id) REFERENCES resume_analysis (id)
);
