-- Persistent storage for interviews.
--
-- Until now the only record of an interview lived in a Python dict in
-- the AI service (_sessions), so every restart lost the questions, the
-- answers, the score and the feedback. The AI service still owns the
-- live session; these tables are the durable copy Spring writes as the
-- interview progresses, and the source of truth for history and
-- progress afterwards.
--
-- This is V3 rather than part of V1 deliberately. An existing database
-- is stamped at baseline version 1 and never replays V1, so tables
-- added there would never appear in it. Everything from V2 onwards
-- reaches existing and fresh databases alike.


-- ==================================================================
-- interview_sessions
--
-- session_id is the AI service's own identifier, carried in every
-- /interview/* request. It is unique so that the answer and finish
-- calls can find the row by it, and so a replayed start cannot create
-- a duplicate.
--
-- score is nullable on purpose. The AI service returns overall_score 0
-- together with evaluated=false when grading fails; storing that zero
-- would drag every average and trend down with a score nobody earned.
-- A failed evaluation stores NULL and is excluded from progress.
-- ==================================================================

CREATE TABLE interview_sessions (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY,
    session_id              character varying(255) NOT NULL,
    user_id                 bigint NOT NULL,
    resume_id               bigint,
    job_description         text,
    status                  character varying(32) NOT NULL,
    current_question_number integer,
    question_count          integer,
    score                   integer,
    feedback_summary        text,
    feedback_json           text,
    started_at              timestamp(6) without time zone NOT NULL,
    completed_at            timestamp(6) without time zone,
    updated_at              timestamp(6) without time zone,

    CONSTRAINT interview_sessions_pkey PRIMARY KEY (id),

    CONSTRAINT uk_interview_sessions_session_id UNIQUE (session_id),

    CONSTRAINT fk_interview_sessions_user
        FOREIGN KEY (user_id) REFERENCES users (id),

    -- Nullable: an interview can be run from pasted resume text with
    -- no stored resume behind it. ON DELETE SET NULL so deleting a
    -- resume does not take the interview history with it.
    CONSTRAINT fk_interview_sessions_resume
        FOREIGN KEY (resume_id) REFERENCES resumes (id) ON DELETE SET NULL,

    CONSTRAINT interview_sessions_status_check
        CHECK (status IN ('active', 'completed', 'cancelled')),

    CONSTRAINT interview_sessions_score_range
        CHECK (score IS NULL OR (score >= 0 AND score <= 100))
);

-- History and progress both read "this user's completed interviews".
CREATE INDEX idx_interview_sessions_user_status
    ON interview_sessions (user_id, status);


-- ==================================================================
-- interview_session_turns
--
-- One row per question, updated in place when the candidate answers
-- it. Mapped as a JPA @ElementCollection of an @Embeddable rather
-- than an entity, so it has no surrogate key of its own - a turn has
-- no identity outside the session that owns it.
--
-- ON DELETE CASCADE mirrors that ownership at the database level.
-- ==================================================================

CREATE TABLE interview_session_turns (
    session_db_id bigint NOT NULL,
    turn_number   integer NOT NULL,
    question      text,
    answer        text,
    reason        text,
    category      character varying(255),
    difficulty    character varying(32),
    answer_mode   character varying(32),
    is_follow_up  boolean,
    answered_at   timestamp(6) without time zone,

    CONSTRAINT fk_interview_session_turns_session
        FOREIGN KEY (session_db_id)
        REFERENCES interview_sessions (id) ON DELETE CASCADE
);

-- Turns are always loaded for one session and ordered by turn_number.
CREATE INDEX idx_interview_session_turns_session
    ON interview_session_turns (session_db_id, turn_number);
